apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "votex.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.service.port }}
          name: redis
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.redis.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.probes.liveness.periodSeconds }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.redis.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.probes.readiness.periodSeconds }}
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
