apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    {{- include "votex.labels" . | nindent 4 }}
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
